{
 "title": "BGP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dev",
    "query": "SHOW TAG VALUES FROM \"openconfig_bgp\" WITH KEY=\"device\""
   },
   {
    "name": "VRF",
    "query": "SHOW TAG VALUES FROM \"openconfig_bgp\" WITH KEY=\"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "$dev  - BGP IPv4 prefixes in VRF $VRF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - IPv4 - $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$VRF$/" },
      { "condition": "AND", "key": "afi_safi_name", "operator": "=", "value": "IPV4_UNICAST" }
     ]
    }
   ]
  },
  {
   "title": "$dev  - BGP IPv6 prefixes in VRF $VRF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - IPv6- $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$VRF$/" },
      { "condition": "AND", "key": "afi_safi_name", "operator": "=", "value": "IPV6_UNICAST" }
     ]
    }
   ]
  },
  {
   "title": "$dev  - BGP EVPN prefixes in VRF $VRF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - EVPN - $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$VRF$/" },
      { "condition": "AND", "key": "afi_safi_name", "operator": "=", "value": "L2VPN_EVPN" }
     ]
    }
   ]
  },
  {
   "title": "$dev  - BGP messages in VRF $VRF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - sent - $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/messages/sent/UPDATE\") FROM \"openconfig_bgp\" WHERE (\"device\" =~ /^$dev$/ AND \"name\" =~ /^$VRF$/) AND $timeFilter GROUP BY time($__interval), \"neighbor_address\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/messages/sent/UPDATE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$VRF$/" }
     ]
    },
    {
     "alias": "$dev - received - $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/messages/sent/UPDATE\") FROM \"openconfig_bgp\" WHERE (\"device\" =~ /^$dev$/ AND \"name\" =~ /^$VRF$/) AND $timeFilter GROUP BY time($__interval), \"neighbor_address\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/messages/received/UPDATE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$VRF$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of BGP  neighbors configured",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "configured",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(*) FROM (SELECT LAST(\"neighbors/neighbor/config/neighbor_address\") FROM \"openconfig_bgp\" GROUP BY \"neighbor_address\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Configured on [[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(*) FROM (SELECT LAST(\"neighbors/neighbor/config/neighbor_address\") FROM \"openconfig_bgp\" GROUP BY \"neighbor_address\") GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "not established",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "not established on [[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP summary ($dev)",
   "type": "table",
   "description": "session state 6 means established (processors.enum.mapping) ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT last(\"neighbors/neighbor/state/session_state\") AS \"session_state\", last(\"neighbors/neighbor/state/established_transitions\") AS \"established_transitions\", last(\"neighbors/neighbor/config/enabled\") AS \"enabled\", last(\"neighbors/neighbor/state/last_established\") AS \"last_established\", last(\"neighbors/neighbor/state/messages/sent/UPDATE\") AS \"update_sent\", last(\"neighbors/neighbor/state/messages/received/UPDATE\") AS \"update_received\", last(\"global/config/as\") AS \"AS\", last(\"global/config/router_id\") AS \"router_id\" FROM \"openconfig_bgp\" WHERE (\"device\" =~ /^$dev$/) AND $timeFilter GROUP BY \"neighbor_address\"",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/messages/sent/UPDATE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sent_update" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  },
  {
   "title": "All BGP sessions state",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "Device $tag_device - Neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/session_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP sessions state for $dev",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "Device $tag_device - Neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/session_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  },
  {
   "title": "All BGP sessions state (6 == ESTABLISHED)",
   "type": "graph",
   "description": "session state 6 means ESTABLISHED \n(processors.enum.mapping)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_device - neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/session_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP sessions state (6 == ESTABLISHED) (Device $dev)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/session_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP transitions to ESTABLISHED (All sessions)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/established_transitions"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP transitions to ESTABLISHED (device $dev)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev - neighbor $tag_neighbor_address",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "neighbor_address" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT mean(\"neighbors/neighbor/state/session_state\") FROM \"openconfig_bgp\" WHERE $timeFilter GROUP BY time($__interval), \"neighbor_address\", \"device\" fill(none)",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/state/established_transitions"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  }
 ]
}